CREATE TABLE PROBLEM(
	SUBJECTKIND CHAR(100),
    UNIT CHAR(40),
    PROBLEMNO INTEGER,
    CONTENT VARCHAR(1000),
    IMAGEPATH CHAR(100),
    SOLUTION VARCHAR(2000),
    RIGHTANSWER CHAR(200),
    RIGHTANSWERIMAGEPATH CHAR(100),
	PRIMARY KEY(SUBJECTKIND,UNIT,PROBLEMNO)
    );

CREATE Table USER (
	USERID CHAR(20),
    USERPW CHAR(20));